name: CI

on:
  merge_group:
    types: [checks_requested]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "**/*.md"
      - '!.github/workflows/ci.yml'
  push:
    branches:
      - main
      - jerry/test
    paths-ignore:
      - "**/*.md"
      - '!.github/workflows/ci.yml'
    tags-ignore:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  get-runner-labels:
    name: Get Runner Labels
    uses: ./.github/workflows/get-runner-labels.yml

  test-windows:
    name: Test Windows
    needs: [get-runner-labels]
    uses: ./.github/workflows/reusable-build.yml
    with:
      target: x86_64-pc-windows-msvc
      profile: "debug"
      runner: ${{ needs.get-runner-labels.outputs.WINDOWS_RUNNER_LABELS }}
      test-diff: true
